In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("dataset.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         501 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.4 KB


In [5]:
housing['CHAS'].value_counts()# categorical data

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.287014   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704648   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.888000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
%matplotlib inline

In [8]:
# For Ploting Histogram
#import matplotlib.pyplot as plt
#housing.hist(bins = 50, figsize = (20,15))

## Train Test Splitting

In [9]:
# For Learning Purpose
import numpy as np
def split_train_test(data,test_ratio):
    np.random.seed(40)# Fix the permutation
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
#train_set,test_set = split_train_test(housing, 0.2)

In [11]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(housing, test_size = 0.2, random_state = 42)

In [12]:
print("Train Length:{train} & test Lenght:{test}".format(train = len(train_set),test = len(test_set)))

Train Length:404 & test Lenght:102


In [13]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(housing, housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [14]:
strat_test_set['CHAS'].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [15]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [16]:
#95/7

In [17]:
#376/28

## Copy training data beacuse we will work on that

In [18]:
housing = strat_train_set.copy()

## Looking for Coorelation
coorelation lies between 1 to -1
+1 means: strong positive coorelation: if one number incerase coresponsd number also increase
-1 means: strong negative coorelation: if one number increase correspond number decrease


In [19]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.679526
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [20]:
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.679526
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [21]:
from pandas.plotting import scatter_matrix
attributes = ['MEDV','RM','ZN','LSTAT']
#scatter_matrix(housing[attributes],figsize = (12,8))

In [22]:
#housing.plot(kind = 'scatter', x = 'RM',y = 'MEDV', alpha = 0.6)

In [23]:
#housing['TAXRM'] = housing['TAX'] / housing['RM']

In [24]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV  
254     16.4  392.89   6.57  21.9  
348     17.0  390.94   5.99  24.5  
476     20.2  396.21  18.68  16.7  
321     19.6  396.90   6.87  23.1  
326     19.6  396.90   6.15  23.0

In [25]:
corr_matrix = housing.corr() # Check TAXRm coorelation
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.679526
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [26]:
#housing.plot(kind = 'scatter', x = 'TAXRM',y = 'MEDV', alpha = 0.6)

In [27]:
housing = strat_train_set.drop('MEDV', axis = 1)
housing_labels = strat_train_set['MEDV'].copy()

In [28]:
housing.shape

(404, 13)

## Missing Attributes

In [29]:
# To take care of missing data,you have three option:
#     1. get rid of missing data
#     2. get rid of whole attributes
#     3. fill missing data with 0 mean or median

In [30]:
# First Option
a = housing.dropna(subset = ['RM'])
a.shape
#a.head()

(399, 13)

In [31]:
# Second Option, drop if this column has week coorelation
b = housing.drop('RM', axis = 1)
b.head()

CRIM    ZN  INDUS  CHAS    NOX   AGE     DIS  RAD  TAX  PTRATIO  \
254  0.04819  80.0   3.64     0  0.392  32.0  9.2203    1  315     16.4   
348  0.01501  80.0   2.01     0  0.435  29.7  8.3440    4  280     17.0   
476  4.87141   0.0  18.10     0  0.614  93.6  2.3053   24  666     20.2   
321  0.18159   0.0   7.38     0  0.493  54.3  4.5404    5  287     19.6   
326  0.30347   0.0   7.38     0  0.493  28.9  5.4159    5  287     19.6   

          B  LSTAT  
254  392.89   6.57  
348  390.94   5.99  
476  396.21  18.68  
321  396.90   6.87  
326  396.90   6.15

In [32]:
# Option Three
median = housing['RM'].median()
median

6.216

In [33]:
#housing['RM'].fillna(median) # Housing data remain unchanged because we have assing

In [34]:
housing.describe() # Before filling missing values

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.282837   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.715645   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086963    0.000000    5.190000    0.000000    0.453000    5.882000   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.216000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [35]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'median')
imputer.fit(housing)

SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='median', verbose=0)

In [36]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21600e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [37]:
X = imputer.transform(housing)

In [38]:
housing_tr = pd.DataFrame(X, columns= housing.columns)

In [39]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX         RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.00000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.28201   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.71123   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.56100   
25%      0.086963    0.000000    5.190000    0.000000    0.453000    5.88475   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.21600   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.63000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.78000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Scikit-learn Design
Primarily, Three types of object
1. Estimators : It estimats some parameter based on dataset. Exm imputer
It has fit and transform method
Fit method: fits the dataset and calculate internal parameters
2. Transformer: Transform methods take inputes and return output based on the learning from fit. It also has convenience function called fit_transform() which fit and transforms.
3. Predictors : Linearregressor is an example of predictors. Fit and predict are two common functions. It also give score function which evaluate the prediction.


## Feature Scaling
Primarily, there are two types of feature scaling method:
1. min-max scaling(Normalization)
(values -min) / (max - min)  # Lies 0-1
2. Standardization:
(values - mean / std)
for this sklearn provide class standardScaler


## Creating a Pipeline

In [40]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy = 'median')),
    # Add as many as you can
    ('std_scaler', StandardScaler())
    
])


In [41]:
housing_num_tr = my_pipeline.fit_transform(housing_tr)

In [42]:
housing_tr.shape

(404, 13)

## Selecting a Desired Model for Our Project

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()


In [44]:
model.fit(housing_num_tr, housing_labels)

C:\Users\Khan\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

## After Trained Model

In [45]:
some_testData = housing.iloc[:5]
some_test_labels = housing_labels.iloc[:5]

In [46]:
prepared_data = my_pipeline.transform(some_testData)

In [47]:
model.predict(prepared_data)

array([22.77, 24.36, 16.21, 23.2 , 23.28])

In [48]:
#some_test_labels
list(some_test_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## Evaluating Models

In [49]:
from sklearn.metrics import mean_squared_error
housing_prediction  = model.predict(housing_num_tr)
lin_mse = mean_squared_error(housing_labels, housing_prediction)
lin_mse = np.sqrt(lin_mse)

In [50]:
lin_mse # Liner Regresoor given: 23.33 not good, DTR,:0.0 (over fiiting)

1.3902934372225735

## Using Better Eveluation Techniques:
How it works:
1 2 3 4 5 : it create  5 group(cv : fold) (example it may more)
it trains 2 3 4 5 and test 1
agian it trains 1 3 4 5 and test 2
 and so on , finalyy returns score

In [51]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_labels, scoring = "neg_mean_squared_error", cv = 10)

In [52]:
rm_error = np.sqrt(-scores)# - because sqrt does not calculate negative value
rm_error

array([2.83577494, 3.07170724, 4.42513084, 3.05402773, 3.4087549 ,
       2.6162325 , 4.7895433 , 3.6885895 , 2.42050666, 3.23736235])

In [53]:
def print_score(score):
    print("Score: ", score)
    print("Mean: ", score.mean())
    print("Std: ", score.std())

In [54]:
print_score(rm_error)

Score:  [2.83577494 3.07170724 4.42513084 3.05402773 3.4087549  2.6162325
 4.7895433  3.6885895  2.42050666 3.23736235]
Mean:  3.3547629963216785
Std:  0.7204577056177324


## Saving Model

In [60]:
from joblib import dump, load
dump(model,"housingModel.joblib")

['housingModel.joblib']

## Tesing Model on test Data

In [64]:
X_test = strat_test_set.drop('MEDV', axis = 1)
y_test = strat_test_set['MEDV'].copy()
X_test_prepared = my_pipeline.transform(X_test)
finale_prediction = model.predict(X_test_prepared)
final_mse = mean_squared_error(y_test, finale_prediction)

In [67]:
final_rmse = np.sqrt(final_mse)
final_rmse

3.19418528076302

In [69]:
finale_prediction

array([24.43, 11.33, 24.34, 21.65, 17.9 , 14.97, 20.82, 15.4 , 31.13,
       43.09, 20.15, 11.46, 23.47, 30.34, 19.79, 10.26, 31.41, 14.27,
       23.2 , 18.22, 19.34, 17.04, 21.32, 20.42, 19.87, 31.47, 15.71,
       32.46,  8.17, 32.2 , 23.29, 21.59, 22.69, 11.25, 22.31, 11.51,
       41.08, 24.61, 22.65, 39.17, 23.89, 31.87, 20.92, 19.7 , 16.89,
       34.76, 45.43, 19.87, 19.99, 21.68, 21.02, 14.59, 21.3 , 14.38,
       24.16, 34.47, 41.07, 28.16, 20.3 , 20.92, 45.69,  8.56, 19.86,
       26.69, 13.19, 32.17, 21.1 , 18.32, 19.24, 33.11, 23.18, 22.44,
       21.24, 22.05, 34.01, 11.02, 15.52, 19.45, 20.5 , 21.78, 23.8 ,
       21.55, 13.69, 23.12, 20.13, 21.49, 13.27, 21.76, 21.57, 22.21,
       17.85, 26.65,  6.27, 27.81, 18.92, 28.52, 19.28, 30.35, 14.63,
       26.29, 22.05, 19.66])

In [72]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24496396, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])